## This assignment is given at the end of first day of workshop 

## We want to read water.xyz file and calculate the distance between each two atoms

In [1]:
import os
file_location = os.path.join('data','water.xyz')
print (file_location)

data\water.xyz


In [2]:
import numpy as np


In [3]:
xyz_file = np.genfromtxt(fname=file_location, skip_header=2,dtype='unicode')

In [7]:
symbols=xyz_file[:,0] #separate symbols from coordinates
coordinates = xyz_file[:,1:]
coordinates = coordinates.astype(np.float)

In [8]:
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
